### ISSUE TITLE
day / night folders counted as images

### ISSUE THREAD

**Issue by Jobieskii** [RAR27/dyn-wall-rs#23]
Using lat / long (either in `config.toml` or using parameters) with images in `day` and `night` folders counts those folders as if images?

_(checking for schedule shows folders as images; when used with 12 pictures returns error stating 14 doesn't divide properly – wrongly counts 2+ entries)_
```
  $ dyn-wall-rs -s Wallpapers/seq
Image: "day" Time: 12:00 a.m.
Image: "1.png" Time: 1:30 a.m.
Image: "2.png" Time: 3:00 a.m.
Image: "3.png" Time: 4:30 a.m.
Image: "4.png" Time: 6:00 a.m.
Image: "5.png" Time: 7:30 a.m.
Image: "6.png" Time: 9:00 a.m.
Image: "7.png" Time: 10:30 a.m.
Image: "8.png" Time: 12:00 p.m.
Image: "9.png" Time: 1:30 p.m.
Image: "night" Time: 3:00 p.m.
Image: "1.png" Time: 4:30 p.m.
Image: "2.png" Time: 6:00 p.m.
Image: "3.png" Time: 7:30 p.m.
Image: "4.png" Time: 9:00 p.m.
Image: "5.png" Time: 10:30 p.m.
```

Possibly because of min_depth being set to 2 after counting, as I understand from the source code:
```
    //min depth of what files should be looked at, will remain as 1 if not syncing with sun, will
    //change to 2 if syncing with sun to ignore the directory names, focusing just on the files
    let mut min_depth = 1;
```
this, yet:
```
let dir_count_night = WalkDir::new(dir_night)
    .min_depth(min_depth)
    .into_iter()
    .count();
let dir_count_day = WalkDir::new(dir_day)
    .min_depth(min_depth)
    .into_iter()
    .count();
times = sun_timings(
    lat,
    args.long.unwrap(),
    args.elevation.unwrap(),
    dir_count_day as u32,
    dir_count_night as u32,
);
min_depth = 2;
```

Also, not sure why day starts at 12:00 a.m. and ends at  3:00 p.m. (no matter the specified long, lat and elevation)

I installed with AUR, version 2.0.2-1, although using --version flag says 2.0.1 (issue with AUR or an oversight?)

**Comment by rehanzo** [comment]
A couple of things here to address:
- with the schedule function, I hadn't necessarily updated it for use with the sun sync functionality, but I definitely should. It was built to be used with the evenly spread changing throughout the day. I'll make sure that this works right with the sun sync functionality. 
- The day starting at 12am and the night starting at 3pm is definitely odd. How do you know when the day and night are starting?
- The AUR package should have the correct version. I'll fix that. Thanks for reporting this.

**Comment by Jobieskii** [comment]
Okay, so I wanted to use 12 (7 + 5) images, but it counts those folders so:
```
dyn-wall-rs -d ~/Wallpapers/seq-test
Cannot schedule the rotation of 14 images evenly throughout the day (the number of images should divide evenly into 1440)
```
I deleted two images to compensate and it set image No 5 (proving the 12am start for day – 15 hours / 7 images * 5th image is 10.71 and my current system time is 10:40)

***

Apparently, specifying coords in `config.toml` does nothing for me – and the 12 am start is in fact just for the standard automatic even spread.

I also realized that I must have been doing something wrong yesterday, as today when I put coords with command parameters it actually works fine. With the only hiccup that I used impossible coordinates for testing which gave a rather incorrect error message: 
```
   $ dyn-wall-rs --lat 150 --long 50 --elevation 250 -d Wallpapers/seq-test  // lat obviously can't be 150
Error with config file: the number of times listed in the config file does not equal the number of files in directory

```
Giving correct command parameters correctly counts 12 images in folders and correctly displays image No.3 (Math checks out)

**Comment by rehanzo** [comment]
Ah, so I see what's happening. 

As it works now, the program first tries to pull arguments from the command line. If there are no arguments from the command line, then it takes it from the config file. So essentially what's happening is that when you're specifying the directory through the command line, it ignores the config file and takes only the command line arguments. Since it only sees the directory that you stated, it then runs the automatic spread. Only field you can mix and match with is the timings field, since that can only be set through the config file. However, now thinking about it, this is definitely confusing for users. I'll make it so that you can kinda mix and match with every field.  A temp solution for you, if you would like to use the config file, is to configure all fields through the config file. Thanks alot for bringing up all these issues. 

Todo:
- ~~fix AUR versioning~~
- ~~Have schedule function be able to give schedule for syncing with sun~~
- ~~allow for mixing and matching for cli args and config file args~~

Again, thanks for bringing all this up. Will definitely help me refine my program.

**Comment by rehanzo** [comment]
Fixed up all the issues that you helped uncover on the new release. Thanks for your help!
